import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@radix-ui/themes/styles.css';
import MainLayout from '../components/layout/MainLayout'
import { Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amhartech commers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className}`}>
        <Theme appearance="dark" >
          <div className="p-7">
            <MainLayout />

            {children}

          </div>
        </Theme>
      </body>
    </html>
  );
}
