import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@radix-ui/themes/styles.css';
import MainLayout from '../components/layout/MainLayout'
import { Theme } from "@radix-ui/themes";
import { Toaster } from "react-hot-toast";
import { notificationOption } from '../lib/notification'
import StoreProvider from "@/lib/StoreProvider";
// import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amhartech commers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className}`}>
        <StoreProvider>
          <Theme appearance="dark" accentColor="indigo" >
            <div className="p-7">
              <MainLayout />

              {children}

            </div>
          </Theme>
        </StoreProvider>

        <Toaster toastOptions={notificationOption} />
      </body>
    </html>
  );
}
